# Transfer Learning MNIST

* Train a simple convnet on the MNIST dataset the first 5 digits [0..4].
* Freeze convolutional layers and fine-tune dense layers for the classification of digits [5..9].

## 1. Import necessary libraries for the model

In [81]:
import pandas as pd
import numpy as np
from keras.datasets import mnist
import tensorflow as tf

## 2. Import MNIST data and create 2 datasets with one dataset having digits from 0 to 4 and other from 5 to 9 

In [54]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [55]:
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)


x_train shape: (60000, 28, 28)
x_test shape: (10000, 28, 28)
y_train shape: (60000,)
y_test shape: (10000,)


In [56]:
x_train_0_4 = x_train[y_train < 5]
x_test_0_4=x_test[y_test<5]
y_train_0_4=y_train[y_train<5]
y_test_0_4=y_test[y_test<5]
x_train_5_9=x_train[y_train>=5]
x_test_5_9=x_test[y_test>=5]
y_train_5_9=y_train[y_train>=5]
y_test_5_9=y_test[y_test>=5]

In [57]:
y_train_0_4

array([0, 4, 1, ..., 2, 1, 3], dtype=uint8)

In [58]:
print('x_train shape:', x_train.shape)

x_train shape: (60000, 28, 28)


## 3. Print x_train, y_train, x_test and y_test for both the datasets

## X and y values for Dataset 1

In [59]:
print(x_train_0_4)
print(x_test_0_4)
print(y_train_0_4)
print(y_test_0_4)


[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

In [60]:
print(x_train_5_9)
print(x_test_5_9)
print(y_train_5_9)
print(y_test_5_9)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

## ** 4. Let us take only the dataset (x_train, y_train, x_test, y_test) for Integers 0 to 4 in MNIST **
## Reshape x_train and x_test to a 4 Dimensional array (channel = 1) to pass it into a Conv2D layer

In [61]:
x_train_0_4 = x_train_0_4.reshape(x_train_0_4.shape[0], 28, 28, 1).astype('float32')# SHape [0] means rows, 28*28*1 because of greyscale
x_test_0_4 = x_test_0_4.reshape(x_test_0_4.shape[0], 28, 28, 1).astype('float32')

## 5. Normalize x_train and x_test by dividing it by 255

In [62]:
x_train_0_4 /= 255 #Done for normalization of data, 
x_test_0_4 /= 255

## 6. Use One-hot encoding to divide y_train and y_test into required no of output classes

In [63]:
from keras.utils import np_utils
y_train_0_4 = np_utils.to_categorical(y_train_0_4, 5)
y_test_0_4 = np_utils.to_categorical(y_test_0_4, 5)

## 7. Build a sequential model with 2 Convolutional layers with 32 kernels of size (3,3) followed by a Max pooling layer of size (2,2) followed by a drop out layer to be trained for classification of digits 0-4  

In [64]:
# Importing the required Keras modules containing model and layers
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
from keras.layers import Flatten, Reshape
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils


In [65]:
# Creating a Sequential Model and adding the layers
model = Sequential()
model.add(Conv2D(32, kernel_size=(3,3), input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))

## 8. Post that flatten the data and add 2 Dense layers with 128 neurons and neurons = output classes with activation = 'relu' and 'softmax' respectively. Add dropout layer inbetween if necessary  

In [66]:
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(5,activation=tf.nn.softmax))

In [67]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Store Training Results
early_stopping = keras.callbacks.EarlyStopping(monitor='val_acc', patience=10, verbose=1, mode='auto')
callback_list = [early_stopping]


## 9. Print the training and test accuracy

In [68]:
BATCH_SIZE = 32
EPOCHS = 10

In [69]:
# Train the model2
model.fit(x_train_0_4, y_train_0_4, batch_size=BATCH_SIZE, nb_epoch=EPOCHS, 
          validation_data=(x_test_0_4, y_test_0_4), callbacks=callback_list)

C:\Users\neeha\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until


Train on 30596 samples, validate on 5139 samples
Epoch 1/10
30596/30596 [==============================] - 21s 679us/step - loss: 0.0969 - acc: 0.9700 - val_loss: 0.0263 - val_acc: 0.9912
Epoch 2/10
30596/30596 [==============================] - 19s 622us/step - loss: 0.0354 - acc: 0.9890 - val_loss: 0.0185 - val_acc: 0.9938
Epoch 3/10
30596/30596 [==============================] - 19s 624us/step - loss: 0.0227 - acc: 0.9932 - val_loss: 0.0210 - val_acc: 0.9930
Epoch 4/10
30596/30596 [==============================] - 19s 624us/step - loss: 0.0160 - acc: 0.9949 - val_loss: 0.0180 - val_acc: 0.9942
Epoch 5/10
30596/30596 [==============================] - 21s 679us/step - loss: 0.0139 - acc: 0.9957 - val_loss: 0.0126 - val_acc: 0.9953
Epoch 6/10
30596/30596 [==============================] - 20s 643us/step - loss: 0.0108 - acc: 0.9967 - val_loss: 0.0115 - val_acc: 0.9965A
Epoch 7/10
30596/30596 [==============================] - 20s 651us/step - loss: 0.0071 - acc: 0.9976 - val_loss: 0.

In [70]:
#Testing the model on train set
score = model.evaluate(x_train_0_4, y_train_0_4)
print('Train loss for 0-4:', score[0])
print('Train accuracy 0-4:', score[1])

30596/30596 [==============================] - 2s 77us/step
Train loss for 0-4: 0.0033080493480874204
Train accuracy 0-4: 0.9987906915936724


In [71]:
#Testing the model on train set
score = model.evaluate(x_test_0_4, y_test_0_4)
print('Test loss 0-4:', score[0])
print('Test accuracy 0-4:', score[1])

5139/5139 [==============================] - 0s 78us/step
Test loss 0-4: 0.015169893184877211
Test accuracy 0-4: 0.994746059625848


## 10. Make only the dense layers to be trainable and convolutional layers to be non-trainable

In [72]:
#Freezing layers in the model which don't have 'dense' in their name
for layer in model.layers:
  if('dense' not in layer.name): #prefix detection to freeze layers which does not have dense
    #Freezing a layer
    layer.trainable = False

#Module to print colourful statements
from termcolor import colored

#Check which layers have been frozen 
for layer in model.layers:
  print (colored(layer.name, 'blue'))
  print (colored(layer.trainable, 'red'))

conv2d_3
False
max_pooling2d_3
False
dropout_5
False
flatten_3
False
dense_5
True
dropout_6
False
dense_6
True


## 11. Use the model trained on 0 to 4 digit classification and train it on the dataset which has digits 5 to 9  (Using Transfer learning keeping only the dense layers to be trainable)

In [73]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Store Training Results
early_stopping = keras.callbacks.EarlyStopping(monitor='val_acc', patience=10, verbose=1, mode='auto')
callback_list = [early_stopping]

In [74]:
x_train_5_9 = x_train_5_9.reshape(x_train_5_9.shape[0],28, 28, 1).astype('float32')# SHape [0] means rows, 28*28*1 because of greyscale
x_test_5_9 = x_test_5_9.reshape(x_test_5_9.shape[0],28, 28, 1).astype('float32')
x_train_5_9 /= 255 #Done for normalization of data, 
x_test_5_9 /= 255

## Subtracing 5 to remove errors in shape

In [75]:
y_train_5_9=y_train_5_9 -5
y_test_5_9=y_test_5_9 -5

In [76]:
from keras.utils import np_utils
y_train_5_9 = np_utils.to_categorical(y_train_5_9, 5)
y_test_5_9 = np_utils.to_categorical(y_test_5_9, 5)

## 12. Print the accuracy for classification of digits 5 to 9

In [77]:
model.fit(x_train_5_9, y_train_5_9, batch_size=BATCH_SIZE, nb_epoch=EPOCHS, 
          validation_data=(x_test_5_9, y_test_5_9), callbacks=callback_list)

C:\Users\neeha\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Train on 29404 samples, validate on 4861 samples
Epoch 1/10
29404/29404 [==============================] - 15s 503us/step - loss: 0.3711 - acc: 0.9162 - val_loss: 0.0725 - val_acc: 0.9780
Epoch 2/10
29404/29404 [==============================] - 14s 471us/step - loss: 0.0708 - acc: 0.9773 - val_loss: 0.0464 - val_acc: 0.9852
Epoch 3/10
29404/29404 [==============================] - 14s 464us/step - loss: 0.0443 - acc: 0.9859 - val_loss: 0.0400 - val_acc: 0.9870
Epoch 4/10
29404/29404 [==============================] - 14s 467us/step - loss: 0.0302 - acc: 0.9903 - val_loss: 0.0327 - val_acc: 0.9905
Epoch 5/10
29404/29404 [==============================] - 14s 479us/step - loss: 0.0240 - acc: 0.9918 - val_loss: 0.0336 - val_acc: 0.9903
Epoch 6/10
29404/29404 [==============================] - 14s 483us/step - loss: 0.0196 - acc: 0.9935 - val_loss: 0.0305 - val_acc: 0.9914
Epoch 7/10
29404/29404 [==============================] - 15s 526us/step - loss: 0.0166 - acc: 0.9938 - val_loss: 0.0

In [78]:
#Testing the model on train set
score = model.evaluate(x_train_5_9, y_train_5_9)
print('Train loss:', score[0])
print('Train accuracy:', score[1])

29404/29404 [==============================] - 2s 81us/step
Train loss: 0.0023713023729727127
Train accuracy: 0.9992858114542239


In [79]:
#Testing the model on train set
score = model.evaluate(x_test_5_9, y_test_5_9)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

4861/4861 [==============================] - 0s 86us/step
Test loss: 0.03211278746644159
Test accuracy: 0.992182678461222


## Sentiment analysis <br> 

The objective of the second problem is to perform Sentiment analysis from the tweets data collected from the users targeted at various mobile devices.
Based on the tweet posted by a user (text), we will classify if the sentiment of the user targeted at a particular mobile device is positive or not.

### 13. Read the dataset (tweets.csv) and drop the NA's while reading the dataset

In [56]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline

In [57]:
import pandas as pd
import numpy as np
import scipy as sp
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from textblob import TextBlob, Word
from nltk.stem.snowball import SnowballStemmer
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [58]:
tweets = pd.read_csv('tweets.csv', engine='python')

In [59]:
tweets.head()

tweet_text  \
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...   
1  @jessedee Know about @fludapp ? Awesome iPad/i...   
2  @swonderlin Can not wait for #iPad 2 also. The...   
3  @sxsw I hope this year's festival isn't as cra...   
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...   

  emotion_in_tweet_is_directed_at  \
0                          iPhone   
1              iPad or iPhone App   
2                            iPad   
3              iPad or iPhone App   
4                          Google   

  is_there_an_emotion_directed_at_a_brand_or_product  
0                                   Negative emotion  
1                                   Positive emotion  
2                                   Positive emotion  
3                                   Negative emotion  
4                                   Positive emotion

In [60]:
tweets=tweets.dropna()

### 14. Preprocess the text and add the preprocessed text in a column with name `text` in the dataframe.

In [61]:
import re

In [62]:
def preprocess(text, remove_digits=False):
    pattern = r'[^a-zA-z0-9\s]' if not remove_digits else r'[^a-zA-z\s]'
    text = re.sub(pattern, '', text)
    return text

In [63]:
preprocess('hello')

'hello'

In [64]:
tweets['text'] = [preprocess(text) for text in tweets.tweet_text]

In [65]:
tweets['text'].head()

0    wesley83 I have a 3G iPhone After 3 hrs tweeti...
1    jessedee Know about fludapp  Awesome iPadiPhon...
2    swonderlin Can not wait for iPad 2 also They s...
3    sxsw I hope this years festival isnt as crashy...
4    sxtxstate great stuff on Fri SXSW Marissa Maye...
Name: text, dtype: object

### 15. Consider only rows having Positive emotion and Negative emotion and remove other rows from the dataframe.

In [66]:
tweets['is_there_an_emotion_directed_at_a_brand_or_product'].unique()

array(['Negative emotion', 'Positive emotion',
       'No emotion toward brand or product', "I can't tell"], dtype=object)

In [67]:
tweets=tweets[~tweets.is_there_an_emotion_directed_at_a_brand_or_product.str.contains("No emotion toward brand or product")]

In [68]:
tweets=tweets[~tweets.is_there_an_emotion_directed_at_a_brand_or_product.str.contains("I can't tell")]

In [69]:
tweets['is_there_an_emotion_directed_at_a_brand_or_product'].unique()

array(['Negative emotion', 'Positive emotion'], dtype=object)

### 16. Represent text as numerical data using `CountVectorizer` and get the document term frequency matrix

#### Use `vect` as the variable name for initialising CountVectorizer.

In [70]:
tweets.columns

Index(['tweet_text', 'emotion_in_tweet_is_directed_at',
       'is_there_an_emotion_directed_at_a_brand_or_product', 'text'],
      dtype='object')

In [71]:
tweets.head(2)

tweet_text  \
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...   
1  @jessedee Know about @fludapp ? Awesome iPad/i...   

  emotion_in_tweet_is_directed_at  \
0                          iPhone   
1              iPad or iPhone App   

  is_there_an_emotion_directed_at_a_brand_or_product  \
0                                   Negative emotion   
1                                   Positive emotion   

                                                text  
0  wesley83 I have a 3G iPhone After 3 hrs tweeti...  
1  jessedee Know about fludapp  Awesome iPadiPhon...

In [72]:
X = tweets.text
y = tweets.is_there_an_emotion_directed_at_a_brand_or_product



In [73]:
vect = CountVectorizer()
vect.fit_transform(tweets['text'])

<3191x6103 sparse matrix of type '<class 'numpy.int64'>'
	with 52449 stored elements in Compressed Sparse Row format>

In [74]:
print(len(vect.get_feature_names()))

6103


In [77]:
# last 50 features
print (vect.get_feature_names()[-50:])

['yep', 'yer', 'yes', 'yesterday', 'yet', 'yield', 'yikes', 'yo', 'yobongo', 'yonkers', 'york', 'you', 'you_', 'youd', 'youll', 'youneedthis', 'youquot', 'your', 'youre', 'yours', 'yourself', 'youtube', 'youve', 'yowza', 'yr', 'yrs', 'yrsday', 'yummy', 'yup', 'zaarly', 'zaarlyiscoming', 'zagg', 'zaggle', 'zappos', 'zazzle', 'zazzlesxsw', 'zazzlsxsw', 'ze', 'zelda', 'zeldman', 'zero', 'zimride', 'zip', 'zite', 'zms', 'zombies', 'zomg', 'zone', 'zoom', 'zzzs']


### 17. Find number of different words in vocabulary

In [78]:
# Total number of words in the vocubukary
print (len(vect.get_feature_names()))

6103


#### Tip: To see all available functions for an Object use dir

In [22]:
dir(vect)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_limit_features',
 '_sort_features',
 '_stop_words_id',
 '_validate_params',
 '_validate_vocabulary',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',


### 18. Find out how many Positive and Negative emotions are there.

Hint: Use value_counts on that column

In [24]:
tweets['is_there_an_emotion_directed_at_a_brand_or_product'].value_counts()

Positive emotion    2672
Negative emotion     519
Name: is_there_an_emotion_directed_at_a_brand_or_product, dtype: int64

### 19. Change the labels for Positive and Negative emotions as 1 and 0 respectively and store in a different column in the same dataframe named 'Label'

Hint: use map on that column and give labels

In [25]:
tweets['label'] = tweets['is_there_an_emotion_directed_at_a_brand_or_product'].map({'Negative emotion':0,'Positive emotion':1})

### 20. Define the feature set (independent variable or X) to be `text` column and `labels` as target (or dependent variable)  and divide into train and test datasets

In [27]:
# define X and y
X = tweets['text']
y = tweets.label

In [30]:
#split the new DataFrame into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [31]:
X_train.shape

(2393,)

In [32]:
y_train.shape

(2393,)

In [34]:
X_train_dtm = vect.fit_transform(X_train)

In [35]:
X_test_dtm = vect.transform(X_test)

## 21. **Predicting the sentiment:**


### Use Naive Bayes and Logistic Regression and their accuracy scores for predicting the sentiment of the given text

In [37]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
# use Naive Bayes to predict the star rating
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)



In [38]:
from sklearn import metrics

In [39]:
# calculate accuracy
print (metrics.accuracy_score(y_test, y_pred_class))

0.8483709273182958


In [40]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[ 34, 111],
       [ 10, 643]], dtype=int64)

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
LR= LogisticRegression()

In [43]:
LR.fit(X_train_dtm, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [45]:
y_pred_class_LR = LR.predict(X_test_dtm)


In [46]:
# calculate accuracy
print (metrics.accuracy_score(y_test, y_pred_class_LR))

0.8646616541353384


In [47]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class_LR)

array([[ 53,  92],
       [ 16, 637]], dtype=int64)

## 22. Create a function called `tokenize_predict` which can take count vectorizer object as input and prints the accuracy for x (text) and y (labels)

In [48]:
def tokenize_predict(vect):
    X_train_dtm = vect.fit_transform(X_train)
    print('Features: ', X_train_dtm.shape[1])
    x_test_dtm = vect.transform(X_test)
    nb = MultinomialNB()
    nb.fit(X_train_dtm, y_train)
    y_pred_class = nb.predict(x_test_dtm)
    print('Accuracy: ', metrics.accuracy_score(y_test, y_pred_class))

In [49]:
tokenize_predict(vect)

Features:  5280
Accuracy:  0.8483709273182958


### Create a count vectorizer function which includes n_grams = 1,2  and pass it to tokenize_predict function to print the accuracy score

In [50]:

# include 1-grams and 2-grams
vect = CountVectorizer(ngram_range=(1, 2))
tokenize_predict(vect)

Features:  25345
Accuracy:  0.8546365914786967


### Create a count vectorizer function with stopwords = 'english'  and pass it to tokenize_predict function to print the accuracy score

In [51]:
vect = CountVectorizer(stop_words='english')
tokenize_predict(vect)

Features:  5042
Accuracy:  0.8533834586466166


### Create a count vectorizer function with stopwords = 'english' and max_features =300  and pass it to tokenize_predict function to print the accuracy score

In [52]:
# include 1-grams and 2-grams
vect = CountVectorizer(stop_words='english',max_features=300)
tokenize_predict(vect)

Features:  300
Accuracy:  0.8208020050125313


### Create a count vectorizer function with n_grams = 1,2  and max_features = 15000  and pass it to tokenize_predict function to print the accuracy score

In [53]:
# include 1-grams and 2-grams
vect = CountVectorizer(ngram_range=(1, 2),max_features=300)
tokenize_predict(vect)

Features:  300
Accuracy:  0.7769423558897243


### Create a count vectorizer function with n_grams = 1,2  and include terms that appear at least 2 times (min_df = 2)  and pass it to tokenize_predict function to print the accuracy score

In [54]:
vect = CountVectorizer(ngram_range=(1, 2),min_df=2)
tokenize_predict(vect)

Features:  7680
Accuracy:  0.8471177944862155
